# Generated by Django 2.0.1 on 2018-01-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='pub_date',
        ),
    ]
