# Generated by Django 2.0.1 on 2018-01-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_neighbor_neighbor_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='target',
        ),
        migrations.AddField(
            model_name='target',
            name='neighbor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor'),
            preserve_default=False,
        ),
    ]
