# Generated by Django 2.0.1 on 2018-01-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180118_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='neighbor',
            new_name='neighbors',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='neighbor_rank',
        ),
    ]
