# Generated by Django 2.0.1 on 2018-01-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180118_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='neighbors',
        ),
        migrations.AddField(
            model_name='neighbor',
            name='neighbor_rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='target',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Target'),
            preserve_default=False,
        ),
    ]
