# Generated by Django 2.0.1 on 2018-01-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180118_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='sdss_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
